name: Execute Notebook Daily

on:
  schedule:
    - cron: '0 13 * * *'  # 7:00 AM CDMX (13:00 UTC)
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install gspread pandas openpyxl gdown schedule
        pip install google-auth google-auth-oauthlib google-auth-httplib2 nbconvert
        pip list  # Verifica las versiones instaladas

    - name: Create credentials file
      env:
        GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
      run: |
        echo '$GOOGLE_SHEETS_CREDS' > service_account.json
        chmod 600 service_account.json
        echo "=== Contenido del service_account.json (primeras líneas) ==="
        head -n 3 service_account.json
        echo "=========================================================="

    - name: Debug environment
      run: |
        echo "=== Variables de entorno ==="
        env
        echo "=== Estructura del repo ==="
        ls -laR
        echo "==========================="

    - name: Execute notebook
      run: |
        set -x  # Modo verbose
        jupyter nbconvert --to python \
          --TagRemovePreprocessor.enabled=True \
          --TagRemovePreprocessor.remove_cell_tags="colab-only" \
          --execute --allow-errors CARGA_AUTOMATICA_DE_DATOS.ipynb
        
        echo "=== Archivos generados ==="
        ls -la
        
        # Ejecutar el script convertido con manejo de errores
        python CARGA_AUTOMATICA_DE_DATOS.py || echo "⚠️ Error en ejecución"

    - name: Upload debug info
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-info-${{ github.run_id }}
        path: |
          service_account.json
          CARGA_AUTOMATICA_DE_DATOS.py
          cambios.log
          nbconvert.log
        retention-days: 3
