name: Execute Notebook Daily

on:
  schedule:
    - cron: '0 13 * * *'  # 7:00 AM CDMX (13:00 UTC)
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Previene ejecuciones eternas

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install gspread pandas openpyxl gdown schedule
        pip install google-auth google-auth-oauthlib google-auth-httplib2 nbconvert

    - name: Create credentials file
      env:
        GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
      run: |
        echo '$GOOGLE_SHEETS_CREDS' > service_account.json
        echo "🔐 Archivo de credenciales creado:"
        ls -la service_account.json

    - name: Convert and execute notebook
      run: |
        # Convertir notebook a script (eliminando celdas de Colab)
        jupyter nbconvert --to python \
          --TagRemovePreprocessor.enabled=True \
          --TagRemovePreprocessor.remove_cell_tags="colab-only" \
          --execute CARGA_AUTOMATICA_DE_DATOS.ipynb

        # Ejecutar directamente (opcional)
        python CARGA_AUTOMATICA_DE_DATOS.py

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: execution-logs
        path: |
          service_account.json
          CARGA_AUTOMATICA_DE_DATOS.py
          cambios.log
