name: Execute Colab Notebook Daily

on:
  schedule:
    - cron: '0 13 * * *'  # 7:00 AM CDMX (13:00 UTC)
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install jupyter nbconvert ipykernel
        pip install gspread pandas openpyxl gdown schedule
        
    - name: Execute notebook
      env:
        GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
      run: |
        jupyter nbconvert --to python --execute CARGA_AUTOMATICA_DE_DATOS.ipynb
        echo "Ejecutado el $(date)" >> execution_log.txt
